name: monetra
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.4
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  syncfusion_flutter_gauges: ^28.2.6
  timeago: ^3.7.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/hero-login.png
    - assets/profile.png
